name: table2gichart
author: Elso 
current: v0.1 
category: utilities 
tags: [google,chart,table,api,interface,table2chart,accessible]
docs: https://github.com/elso/table2gichart/blob/master/README.md
demo: http://elso.github.io/table2gichart
